config/routes.rb
Cholula::Application.routes.draw do
  resources :annot_comments

  get "users/show"
  devise_for :users
  get "welcome/index"
  
  resources :books do
	member do
		post 'create_annotation'
	end	
  end
  
 resources :users

 resources :annotations do
  member do
    post 'create_annotcomment'
  end
end
  
  root to: "welcome#index"
  

  

end

app/models/annot_comment.rb
class AnnotComment < ActiveRecord::Base
	belongs_to :annot_comment
	belongs_to :annotation
	belongs_to :user
	has_many :annot_comments
end

app/controllers/annot_comments_controller.rb
class AnnotCommentsController < ApplicationController
  before_action :set_annot_comment, only: [:show, :edit, :update, :destroy]


  # GET /annot_comments
  # GET /annot_comments.json
  def index
    @annot_comments = AnnotComment.all
  end

  # GET /annot_comments/1
  # GET /annot_comments/1.json
  def show
  end

  # GET /annot_comments/new
  def new
    @annot_comment = AnnotComment.new
  end

  # GET /annot_comments/1/edit
  def edit
  end

  # POST /annot_comments
  # POST /annot_comments.json
  def create
    @annot_comment = AnnotComment.new(annot_comment_params)

    respond_to do |format|
      if @annot_comment.save
        format.html { redirect_to @annot_comment, notice: 'Annot comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @annot_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @annot_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annot_comments/1
  # PATCH/PUT /annot_comments/1.json
  def update
    respond_to do |format|
      if @annot_comment.update(annot_comment_params)
        format.html { redirect_to @annot_comment, notice: 'Annot comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @annot_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annot_comments/1
  # DELETE /annot_comments/1.json
  def destroy
    @annot_comment.destroy
    respond_to do |format|
      format.html { redirect_to annot_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annot_comment
      @annot_comment = AnnotComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annot_comment_params
      params.require(:annot_comment).permit(:body)
    end
end

app/helpers/annot_comments_helper.rb
module AnnotCommentsHelper
end

app/views/annot_comments/_form.html.erb
<%= form_for(@annot_comment) do |f| %>
  <% if @annot_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annot_comment.errors.count, "error") %> prohibited this annot_comment from being saved:</h2>

      <ul>
      <% @annot_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annot_comments/edit.html.erb
<h1>Editing annot_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @annot_comment %> |
<%= link_to 'Back', annot_comments_path %>

app/views/annot_comments/index.html.erb
<h1>Listing annot_comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @annot_comments.each do |annot_comment| %>
      <tr>
        <td><%= annot_comment.body %></td>
        <td><%= link_to 'Show', annot_comment %></td>
        <td><%= link_to 'Edit', edit_annot_comment_path(annot_comment) %></td>
        <td><%= link_to 'Destroy', annot_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annot comment', new_annot_comment_path %>

app/views/annot_comments/new.html.erb
<h1>New annot_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', annot_comments_path %>

app/views/annot_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @annot_comment.body %>
</p>

<%= link_to 'Edit', edit_annot_comment_path(@annot_comment) %> |
<%= link_to 'Back', annot_comments_path %>