config/routes.rb
Cholula::Application.routes.draw do
  resources :annot_comments

  get "users/show"
  devise_for :users
  get "welcome/index"
  
  resources :books do
	member do
		post 'create_annotation'
	end	
  end
  
 resources :users

 resources :annotations do
  member do
    post 'create_annotcomment'
  end
end
  
  root to: "welcome#index"
  

  

end

app/models/book.rb
class Book < ActiveRecord::Base

has_many :analyses

end

app/controllers/books_controller.rb
#require 'epub-parser-0.1.5'
include ActionView::Helpers::AssetTagHelper

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
	
	respond_to :json

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
  
  def create_annotation
  
  	@book = Book.find(params[:id])
  	if (user_signed_in?) 
    
  		analysis = Analysis.find_by_user_id_and_book_id(current_user, @book)
  		if (analysis == nil)
  			analysis = Analysis.new(:user_id => current_user, :book => @book)
  		end
  		
  		# todo: prevent people from spamming the same annotation over and over again
  		#if (analysis.annotations.empty?)
  			@annotation = Annotation.create(:body => params[:body], :quoted_text => params[:quoted_text], :user => current_user, :book => @book, :analysis => analysis)
  		#else
  		#	analysis.annotations.find_by_user_id
  		#end
  		render :json => @annotation.to_json # pass information back to AJAX form
  		
  		respond_to do |format|
  			format.js {}
  			format.html { render :action => "show" } 
  		end
  		
    else 
  		respond_to do |format|
  			format.html { redirect_to @book, notice: 'Not logged in.' }
      end
  	
  	end 
	
  end
  

  def epub
    send_file "perks_of_wallflower.epub"
  end

  def epub
    send_file "perks_of_wallflower.epub"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :content)
    end
end

app/helpers/books_helper.rb
module BooksHelper

# feather_width = 3

def all_annotations(book)

	annotations = Array.new
	book.analyses.each do |a|
		a.annotations.each do |anno|
			annotations << anno
		end
	end

	return annotations
end

# def words(book)

	# str = book.text
	# str.gsub(/\s+/m, ' ').strip.split(" ")
	# return str
	
# end

# def regions(book)

	# markers = Array.new(words(book).size, 0)

	# for i in 0..words(book).size
		# a = book.all_annotations(book)[i]
		
		# if abs(a.location_start - i) <= feather_width
			# markers[i]++
		# end
		
	# end
	
	# regions = Array.new #indices at which annotation regions END
	
	# region_found = false
	# greatest = 0
	# for i in 0..words(book).size
		# greatest = max(greatest, markers[i])
		
		# if markers[i] > 0 and not region_found
			# region_found = true
		# end
		
		# if region_found and markers[i] == 0
			# markers[i-1] = greatest
			# regions << i-1  # note: num of annotations in region[n] is markers[region[n]-1]
			# region_found = false
		# end
		
	# end

# end

end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.author %></td>
        <td><%= book.title %></td>
        <td><%= truncate(book.content, length: 120, separator: ' ') %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
</br>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<script type = "text/javascript">


/*$(document).ready(function() {
    $('div').onclick(function() {
        $('div').getSelectionText();
    });
});

function getSelectionText() {
    var text = "";
    if (window.getSelection) {
        text = window.getSelection().toString();
    } else if (document.selection && document.selection.type != "Control") {
        text = document.selection.createRange().text;
    }
	
	var str = document.URL;
	
	str = str.replace(/\?highlight\=/g, '');
	
	if (str.indexOf("?highlight=") != -1) {
		str = str.split("?highlight=")[0];
	}
	
	window.location.href = str + "?highlight=" + text;
	
    return text;
}

function selectText(element) {
    var doc = document
        , text = doc.getElementById(element)
        , range, selection
    ;    
    if (doc.body.createTextRange) { //ms
        range = doc.body.createTextRange();
        range.moveToElementText(text);
        range.select();
    } else if (window.getSelection) { //all others
        selection = window.getSelection();        
        range = doc.createRange();
        range.selectNodeContents(text);
        selection.removeAllRanges();
        selection.addRange(range);
    }
} */


/** wrapper of the dialog object that helps handle
operations */
function DialogHandler(elem, opt)
{
    this.dialog = $("#" + elem).dialog(opt);
}

DialogHandler.prototype.run = function(range)
{
    this.dialog.dialog("open");
    $("#dialog_quote").val(range);
}

DialogHandler.prototype.close = function()
{
    this.dialog.dialog("close");

    //also clear the textarea of text
}

var Book = null;
var mode = 1;
var Renderer = EPUBJS.Renderer; 
//EPUBJS.filePath = "../";
$(document).ready(function() {

    //initialize dialog
    var opt = {
        autoOpen:false,
        close: function(event, ui)
        {
            $(Book.render.bodyEl).getHighlighter().removeHighlights();
        }
    };
    var dh = new DialogHandler("dialog", opt);


    Book = ePub("../perks_of_wallflower.epub"); // loading of the epub

    Book.renderTo("body_text", dh);
    Book.setDialogCallback(dh);
    Book.getToc().then(function (toc)
    {
        toc.forEach(function(entry)
        {
            var d = document.createElement("div");
            $(d).attr("class", "toc_heading");
            var a = document.createElement("a");
            a.innerHTML = entry.label;
            $(a).attr("href", "javascript:void(0)");
            $(a).attr("onclick", "Book.goto('" + entry.href + "');");
            $(d).append(a);
            $("#toc_panel").append(d);
        });
    });

    $(".btn-group > .btn").on("click", function()
    {
        if(this.id == "mode_read")
        {
            mode = 0;
            var bodyel = Book.render.bodyEl;
            $(bodyel).getHighlighter().removeHighlights();
        }
        else if(this.id == "mode_annot")
        {
            mode = 1;
        }
    });
	

    //when you submit the dialog box
	$(".btn btn-default").click(function() { 
		$('#dialog_form').submit(function() {  
		var valuesToSubmit = $(this).serialize();
		$.ajax({
			url: $(this).attr('action'), //sumbits it to the given url of the form
			data: valuesToSubmit,
			dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
		}).success(function(json){
			alert("hi!")
			alert(json);
		});
		
		//alert(xmlhttp.responseText);
		return false; // prevents normal behaviour
	}
	);
});
	
});

</script>


<div class="titlebar">
  <%= @book.title %>
  by <%= @book.author %>
</div>
<div class="toolbar">
    <div class="toolbar_btn_w">
        <div class="toolbar_btn">
            <div class="btn-group">
              <button type="button" class="btn btn-default" id="mode_read">Read Mode</button>
              <button type="button" class="btn btn-default" id="mode_annot">Annotation Mode</button>
            </div>
        </div>
    </div>
</div>
<div class="reader_container">
    <div class="reader_panel" id="reader_panel1">
        <div class="reader_paneltext" id="toc_panel">
            <div class="toc_title">Table of Contents</div>
        </div>
    </div>
    <div class="reader_body">
        <div class="reader_arrow" id="prev_page">
            <a href="javascript:void(0)" onclick="Book.prevPage();">B</a>
        </div>
        <div class="reader_bodytext_w">
            <div class="reader_bodytext" id="body_text">
                <div id="dialog" title="Add annotation">
						<%= form_tag({:controller => "books", :action => "create_annotation"}, { :id => "dialog_form" , :remote => true} ) do  %>
						
					    <div><%= text_area_tag(:quoted_text, nil, :class => "form-control", :readonly => "true", :id => "dialog_quote", :size => "20x5") %></div>
                        <div><%= text_area_tag(:body, nil, :class => "form-control", :size => "20x5", :placeholder => "Enter analysis here") %></div>
					 
                        <div>
                            <%= radio_button_tag(:publish_status, "with all credentials") %>
                        </div>
                        <div>
                            <%= radio_button_tag(:publish_status, "with name only") %>
                        </div>
                        <div>
                            <%= radio_button_tag(:publish_status, "anonymously") %>
                        </div>
                        <div>
                            <%= button_tag "Publish", :class => "btn btn-default" %>
                        </div>
						<% end %>

                </div>
            </div>
        </div>
        <div class="reader_arrow" id="next_page">
            <a href="javascript:void(0)" onclick="Book.nextPage();">N</a>
        </div>
    </div>
    <div class="reader_panel" id="reader_panel2">
        <div class="reader_paneltext" id="annot_panel"> 
            <div id="annot_panel_title">Annotations</div>
            <div class="annot_list">
                
                <!-- one annotation block !-->
				<% @book.analyses.each do |a| %>
				<% a.annotations.each do |anno| %>

                <div class="annot_w">
                    <div class="annot">
                        <div class="annot_section" id="annot_left">
                            <div>
                                up
                            </div>
                            <div>
                                score
                            </div>
                            <div>
                                down
                            </div>
                        </div>
                        <div class="annot_section" id="annot_mid">
                            <div class="annot_quote">"<%= anno.quoted_text %>"</div>
                            <div class="annot_desc"><%= anno.body %></div>
							<div> posted by <%= link_to anno.user.email, user_path(anno.user) %></div>

                            <div class="annot_details">
                                <div class="annot_details_d">
                                    122 Comments
                                </div>
                                <div class="annot_details_d">
                                    Reply
                                </div>
                                <div class="annot_details_d">
                                    Share
                                </div>
                            </div>
                        </div>
                        <div class="annot_section" id="annot_right">
                            <%= link_to '>> discuss in detail', annotation_path(anno) %>
                        </div>
                    </div>
                </div>

				<% end %>
				<% end %>

            </div>
        </div>
    </div>
</div>

num analyses = <%= @book.analyses.size %></br>
num annotations = <%= all_annotations(@book).size %></br>

</br>

</br>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>