config/routes.rb
Cholula::Application.routes.draw do
  resources :annot_comments

  get "users/show"
  devise_for :users
  get "welcome/index"
  
  resources :books do
	member do
		post 'create_annotation'
	end	
  end
  
 resources :users

 resources :annotations do
  member do
    post 'create_annotcomment'
  end
end
  
  root to: "welcome#index"
  

  

end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  belongs_to :book
  belongs_to :analysis
  belongs_to :user

  has_many :annot_comments
  
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: [:show, :edit, :update, :destroy]

  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.all
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
  end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to @annotation, notice: 'Annotation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @annotation }
      else
        format.html { render action: 'new' }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1
  # PATCH/PUT /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to @annotation, notice: 'Annotation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1
  # DELETE /annotations/1.json
  def destroy
    @annotation.destroy
    respond_to do |format|
      format.html { redirect_to annotations_url }
      format.json { head :no_content }
    end
  end

  def create_annotcomment
    @annotation = Annotation.find(params[:id])
    if(user_signed_in?)

      #note: like the annotations, we have to prevent people from spamming comments
      @annot_comment = AnnotComment.create(:body => params[:body], :user => current_user, :annotation => @annotation)

      respond_to do |format|
        format.js {}
        format.html { render :action => "show" } 
      end

    else
      respond_to do |format|
        format.html { redirect_to @annotation, notice: 'Not logged in.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annotation_params
      params[:annotation]
    end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/views/annotations/_form.html.erb
<%= form_for(@annotation) do |f| %>
  <% if @annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% @annotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<h1>Listing annotations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= link_to 'Show', annotation %></td>
        <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
        <td><%= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New annotation</h1>

<%= render 'form' %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="annot_container">

	<h1>Annotations</h1>

	<div class="annot_main">
		<div class="annot_qt">
			"<%= @annotation.quoted_text %>"
		</div>
		<div class="annot_body">
			<%= @annotation.body %>
		</div>
	</div>

	<div class="annotc_container">
		<div class="annotc_submit">
			<%= form_tag({:controller => "annotations", :action => "create_annotcomment"}, { :id => "annotc_form" , :remote => true} ) do  %>	
			    	<%= text_area_tag(:body, nil, :id => "annotc_text", :size => "40x6") %>
                    <%= submit_tag "Submit", :class => "btn btn-default" %>
			<% end %>
		</div>
		<div class="annotc_main">
			<% @annotation.annot_comments.each do |comment| %>
				<div class='annotc_c'>
					<div class='annotc_cheader'>
						<%= comment.user.email %>
					</div>
					<div class='annotc_cbody'>
						<%= comment.body %>
					</div>
					<div class='annotc_cfooter'>
						Reply Save Share
					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>

<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>